### ISSUE TITLE
Backward-compatibility issue

### ISSUE THREAD

**Issue by raven2cz** [mk-fg/python-pulse-control#78]
Is it really necessary to make not backward-compatible changes in API?
```
AttributeError: module 'pulsectl._pulsectl' has no attribute 'PA_SAMPLE_FLOAT32BE'. Did you mean: 'PA_SAMPLE_FLOAT32NE'?
```
present in `volctl` after your last change in package

https://aur.archlinux.org/packages/python-pulsectl#comment-913427

It worked with python 3.11 yesterday already. It is not possible to run it today. Is it possible to ensure backward compatibility?

I'm not sure how much apps can this incompatibility change destroyed. Can you explain the reasons for it and what are migration steps? Thanks.

**Comment by mk-fg** [comment]
pulsectl._pulsectl is NOT a public API.
